apiVersion: v1
kind: Service
metadata:
  name: confluence
spec:
  ports:
    - name: "confluence"
      port: 80
      targetPort: 8090
    - name: "synchrony"
      port: 8091
  selector:
    app: confluence
  type: LoadBalancer
  sessionAffinity: ClientIP